# Generated by Django 3.2.9 on 2022-05-28 15:14

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Контактную информацию', 'verbose_name_plural': 'Контактная информация'},
        ),
        migrations.AlterField(
            model_name='info',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона'),
        ),
    ]
