# Generated by Django 3.2.9 on 2022-06-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='clients', verbose_name='Лого клиента')),
            ],
            options={
                'verbose_name': 'Клиенты',
                'verbose_name_plural': 'Клиента',
            },
        ),
    ]
