# Generated by Django 3.2.9 on 2022-06-12 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'Клиента', 'verbose_name_plural': 'Клиенты'},
        ),
    ]
