# Generated by Django 3.2.9 on 2022-04-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Диаметр')),
            ],
        ),
        migrations.CreateModel(
            name='Liter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liter', models.IntegerField(verbose_name='Литр')),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Метр')),
            ],
        ),
    ]
