# Generated by Django 3.2.9 on 2022-04-10 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diameter',
            options={'verbose_name': 'Диаметр'},
        ),
        migrations.AlterModelOptions(
            name='liter',
            options={'verbose_name': 'Литр'},
        ),
        migrations.AlterModelOptions(
            name='meter',
            options={'verbose_name': 'Метр'},
        ),
    ]
