# Generated by Django 3.2.9 on 2022-06-02 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_kg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diameter',
            options={'verbose_name': 'Диаметр', 'verbose_name_plural': 'Диаметр'},
        ),
        migrations.AlterModelOptions(
            name='kg',
            options={'verbose_name': 'Вес', 'verbose_name_plural': 'Вес'},
        ),
        migrations.AlterModelOptions(
            name='liter',
            options={'verbose_name': 'Литр', 'verbose_name_plural': 'Литр'},
        ),
        migrations.AlterModelOptions(
            name='meter',
            options={'verbose_name': 'Метр', 'verbose_name_plural': 'Метр'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Размер', 'verbose_name_plural': 'Размер'},
        ),
    ]
