# Generated by Django 3.2.9 on 2022-03-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='img',
            field=models.SlugField(default=1, max_length=60, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
