# Generated by Django 3.2.9 on 2022-03-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_slider_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='img',
            field=models.URLField(max_length=256, verbose_name='Ссылка на фото'),
        ),
    ]
