# Generated by Django 3.2.9 on 2022-04-09 10:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20220408_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
