# Generated by Django 3.2.9 on 2022-04-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20220410_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='diameter',
        ),
        migrations.RemoveField(
            model_name='product',
            name='liter',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meter',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='diameter',
            field=models.BooleanField(default=False, verbose_name='Диаметр'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='liter',
            field=models.BooleanField(default=False, verbose_name='Литр'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='meter',
            field=models.BooleanField(default=False, verbose_name='Метр'),
        ),
    ]
