# Generated by Django 3.2.9 on 2022-04-10 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20220410_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='size',
            field=models.BooleanField(default=False, verbose_name='Размер'),
        ),
    ]
