# Generated by Django 3.2.9 on 2022-04-10 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220410_0109'),
        ('products', '0013_subcategory_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='diameter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.diameter', verbose_name='Диаметр'),
        ),
        migrations.AddField(
            model_name='product',
            name='liter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.liter', verbose_name='Литр'),
        ),
        migrations.AddField(
            model_name='product',
            name='meter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.meter', verbose_name='Метр'),
        ),
    ]
