# Generated by Django 3.2.9 on 2022-04-10 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_size'),
        ('products', '0014_auto_20220410_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.size', verbose_name='Размер'),
        ),
    ]
