# Generated by Django 3.2.9 on 2022-05-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20220524_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.URLField(default='https://cdn-icons-png.flaticon.com/512/4054/4054617.png', max_length=256, verbose_name='Ссылка на фото'),
            preserve_default=False,
        ),
    ]
