# Generated by Django 3.2.9 on 2022-06-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_category_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(max_length=256, upload_to='', verbose_name='фото категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(max_length=256, upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='img',
            field=models.ImageField(max_length=256, upload_to='', verbose_name='Фото слайдера'),
        ),
    ]
