# Generated by Django 3.2.9 on 2022-06-02 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20220602_0651'),
        ('products', '0021_auto_20220602_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.kg', verbose_name='Вес/кг'),
        ),
    ]
