# Generated by Django 3.2.9 on 2022-06-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_product_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='kg',
            field=models.BooleanField(default=False, verbose_name='Вес/кг'),
        ),
    ]
