# Generated by Django 3.2.9 on 2022-06-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.TextField(default=1, help_text='Для отобрадения похожих постов.', verbose_name='Теги'),
            preserve_default=False,
        ),
    ]
